#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo
echo ":: Deploy"

#  Source utility functions.
source "$OPENSHIFT_REPO_DIR/.openshift/tools/custom_nodejs_version"

#  Ensure custom node version if not installed.
ensure_node_is_installed

echo
